import { Inter } from "next/font/google";
//IMORT FROM "./globals.css";
import styles from "../styles/Layout.module.css"
import Nav from "@/components/Nav"
import "./globals.css";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CHELSEA FC",
  description: "Generated by CHELSEA FC",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav />
        <div className={styles.container}>
            <main className={styles.main}>
                <Header />
                {children}
            </main>
        </div>
      </body>
    </html>
  );
}
